services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.3"
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes:
      - esVolume:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  wappalyzer-fetch:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c './wait-for elasticsearch:9200 -- node app.js'
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  esVolume:
    driver: local
