services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.3"
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes:
      - esVolume:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.13.3"
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch

  wappalyzer-fetch:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    init: true
    volumes:
      - ./crontab:/var/spool/cron/crontabs/root

volumes:
  esVolume:
    driver: local
