---
version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  wappalyzer-fetch:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
